const a = 3
const b = "3"
const c = 1
console.log('igual' ,a==b)
console.log('identico', a===b) 
console.log('diferente' ,a!=b)
console.log('não identico', a!==b) 
console.log('menor', a < b) 
console.log('menor ou igual', a <= b) 
console.log('maior', a > b) 
console.log('maior ou igual', a >= b) 
console.info('Tabela Verdade E')
console.log('E - V V', a == b && a <= b)
console.log('E - F V', a === b && a <= b)
console.log('E - V F', a == b && a > b)
console.log('E - F F', a === b && a < b)
console.info('Tabela Verdade OU')
console.log('E - V V', a == b || a <= b)
console.log('E - V F', a == b || a < b)
console.log('E - F V', a === b || a >= b)
console.log('E - F F', a === b || a > b)
console.info('Tabela Verdade NOT')
console.log('NOT - V', !(a == b))
console.log('NOT - F', !(a === b))